[[redirects]]
  from = "https://sajjadraza786.netlify.app"
  to = "https://sajjad.gq"
  status = 301
  force = true
  
  [[plugins]]
package = "@netlify/plugin-sitemap"

[plugins.inputs]
  buildDir = "/"
  
  [build]
  publish = "/"

[[plugins]]
  package = "netlify-plugin-submit-sitemap"

	[plugins.inputs]

	# The base url of your site (optional, default = main URL set in Netlify)
	baseUrl = "https://sajjad.gq"

	# Path to the sitemap URL (optional, default = /sitemap.xml)
	sitemapPath = "/sitemap.xml"

	# Enabled providers to submit sitemap to (optional, default = 'google', 'bing', 'yandex'). Possible providers are currently only 'google', 'bing', 'yandex'.
	providers = [
		"google",
		"bing",
		"yandex"
	]

[[plugins]]
package = "netlify-plugin-image-optim"

[build]
  publish = "/"

[[plugins]]
  package = "netlify-plugin-gatsby-cache"
  
  [build]
  publish = "/"

[[plugins]]
  package = "netlify-plugin-gridsome-cache"
  
 
