[[redirects]]
  from = "https://sajjadraza786.netlify.app"
  to = "https://sajjad.gq"
  status = 301
  force = true
  
  [[plugins]]
package = "@netlify/plugin-sitemap"

  [plugins.inputs]
  buildDir = "public"
  # disable pretty URLS and keep `index.html` & trailing `.html` file references in paths
  prettyURLs = false
